version: "3.7"
services:
  web:
    container_name: flask-api
    build: .
    ports:
      - 5100:5100
    depends_on:
      - mongodb
    volumes:
      - .:/app
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db

volumes:
  db-data:
